pool:
  name: Azure Pipelines
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

stages:
  - stage: BuildApp
    displayName: Build App
    jobs:
      #- template: templates/app-build.yml@templates
      - job:
        pool:
          name: Azure Pipelines
          vmImage: 'windows-latest'
        steps:
          - task: NuGetToolInstaller@1

          - task: NuGetCommand@2
            inputs:
              restoreSolution: '$(solution)'

          - task: VSBuild@1
            inputs:
              solution: '$(solution)'
              msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="$(build.artifactStagingDirectory)\WebApp.zip" /p:DeployIisAppPath="Default Web Site"'
              platform: '$(buildPlatform)'
              configuration: '$(buildConfiguration)'

          - task: CopyFiles@2
            inputs:
              SourceFolder: 'tests'
              Contents: '**'
              TargetFolder: '$(Build.ArtifactStagingDirectory)/tests'

          - task: DotNetCoreCLI@2
            inputs:
              command: publish
              publishWebProjects: True
              arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
              zipAfterPublish: True

          - task: PublishPipelineArtifact@1
            inputs:
              targetPath: '$(Build.ArtifactStagingDirectory)'
              artifactName: 'checkYourEligibility-Admin'

  - stage: DeployAppCypress
    displayName: Deploy App Cypress
    jobs:
      - deployment: cypressdeploy
        displayName: Deploy App Cypress
        pool:
          name: Azure Pipelines
          vmImage: 'ubuntu-latest'
        environment: CYPRESS
        strategy:
          runOnce:
            preDeploy:
              steps:
                - task: DownloadPipelineArtifact@2
                  inputs:
                    buildType: 'current'
                    targetPath: '$(Pipeline.Workspace)'
            deploy:
              steps:
                - task: AzureRmWebAppDeployment@4
                  inputs:
                    ConnectionType: 'AzureRM'
                    azureSubscription: 's203d.azdo.deployment'
                    appType: 'webApp'
                    WebAppName: 'ece-dev-as-cypress'
                    packageForLinux: '$(Pipeline.Workspace)/checkYourEligibility-Admin/CheckYourEligibility-Admin.zip'
                - task: Bash@3
                  inputs:
                    targetType: inline
                    script: |
                      cd $(Pipeline.Workspace)/checkYourEligibility-Admin/tests
                      npm install
                - task: Bash@3
                  displayName: 'RunTests'
                  inputs:
                    targetType: inline
                    script: |
                      cd $(Pipeline.Workspace)/checkYourEligibility-Admin/tests
                      export CYPRESS_BASE_URL="$(CYPRESS_BASE_URL_CYPRESS)"
                      export CYPRESS_DFE_ADMIN_EMAIL_ADDRESS="$(DFE_ADMIN_EMAIL_ADDRESS)"
                      export CYPRESS_DFE_ADMIN_PASSWORD="$(DFE_ADMIN_PASSWORD)"
                      npm run adminE2e:electron
                - task: Bash@3
                  condition: always()
                  displayName: 'Generate report'
                  inputs:
                    targetType: inline
                    script: |
                      cd $(Pipeline.Workspace)/checkYourEligibility-Admin/tests
                      npm run combine:reports
      
                - task: PublishTestResults@2
                  condition: always()
                  displayName: 'Publish test results'
                  inputs:
                    testResultsFiles: |
                      **/combined-report.xml
                      **/screenshots/
                    searchFolder: '$(Pipeline.Workspace)/checkYourEligibility-Admin/tests'
