//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CheckYourEligibility_Parent.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CheckYourEligibility_Parent.Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent National Insurance Number,Parent asylum seeker reference number,Parent Date of Birth,Parent Last Name
        ///AB123456C,,01/01/1990,SIMPSON
        ///AB123456D,,01/01/1990,smith
        ///.
        /// </summary>
        internal static string batchchecktemplate_small_Valid {
            get {
                return ResourceManager.GetString("batchchecktemplate_small_Valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent National Insurance Number,Parent asylum seeker reference number,Parent Date of Birth,Parent Last Name
        ///AB123456C,,1990-01-01,SIMPSON,
        ///ABCD,,1990-01-01,Jones
        ///AB123456D,,32/01/1990,smith,
        ///,,1990-01-01,flower
        ///.
        /// </summary>
        internal static string batchchecktemplate_some_invalid_items {
            get {
                return ResourceManager.GetString("batchchecktemplate some invalid items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent National Insurance Number,Parent asylum seeker reference number,Parent Date of Birth,Parent Last Name
        ///AB123456E,,01/01/2000,SIMPSON
        ///AC123456D,,02/01/2000,GRIFFIN
        ///AB123456C,,03/01/2000,SIMPSON
        ///AC123456D,,04/01/2000,GRIFFIN
        ///AB123456C,,05/01/2000,SIMPSON
        ///AC123456D,,06/01/2000,GRIFFIN
        ///AB123456C,,07/01/2000,SIMPSON
        ///AC123456D,,08/01/2000,GRIFFIN
        ///AB123456C,,09/01/2000,SIMPSON
        ///AC123456D,,10/01/2000,GRIFFIN
        ///AB123456C,,11/01/2000,SIMPSON
        ///AC123456D,,12/01/2000,GRIFFIN
        ///AB123456C,,13/01/2000,SIMPSON        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string batchchecktemplate_too_many_records {
            get {
                return ResourceManager.GetString("batchchecktemplate_too_many_records", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;id&quot;:&quot;4579AE90-8B2B-4C02-AC08-756CBBB1C567&quot;,&quot;name&quot;:&quot;Hollinswood Primary School&quot;,&quot;LegalName&quot;:&quot;HOLLINSWOOD PRIMARY SCHOOL&quot;,&quot;category&quot;:{&quot;id&quot;:&quot;001&quot;,&quot;name&quot;:&quot;Establishment&quot;},&quot;type&quot;:{&quot;id&quot;:&quot;01&quot;,&quot;name&quot;:&quot;Community School&quot;},&quot;urn&quot;:&quot;123456&quot;,&quot;uid&quot;:null,&quot;upin&quot;:null,&quot;ukprn&quot;:&quot;10069246&quot;,&quot;establishmentNumber&quot;:&quot;2200&quot;,&quot;status&quot;:{&quot;id&quot;:1,&quot;name&quot;:&quot;Open&quot;},&quot;closedOn&quot;:null,&quot;address&quot;:&quot;Dale Acre Way, Hollinswood, Telford, Shropshire, TF3 2EP&quot;,&quot;telephone&quot;:&quot;01952386920&quot;,&quot;region&quot;:{&quot;id&quot;:&quot;F&quot;,&quot;name&quot;:&quot;West Midlands&quot;},&quot;localAuthority&quot;:{&quot;id&quot;:&quot;24 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ClaimSchool {
            get {
                return ResourceManager.GetString("ClaimSchool", resourceCulture);
            }
        }
    }
}
